# Generated by Django 4.2 on 2023-04-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=120)),
                ('l_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('z_code', models.CharField(max_length=100)),
                ('number_1', models.CharField(max_length=50)),
                ('number_2', models.CharField(max_length=50)),
            ],
        ),
    ]
